apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus # This UID must match what is referenced in your dashboard JSON
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: true 