version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2

  app1:
    build: ./app1
    environment:
      - FLASK_ENV=production
    depends_on:
      - redis

  app2:
    build: ./app1  # Reusing the same app code
    environment:
      - FLASK_ENV=production
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379" 